POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Energy",
    "author": "Test Test",
	"url": "www.facebook.com",
	"likes": 12,
	"userId": "624ef410690edf7d8186c95f"
}