POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyNGYxMjE2ZWMwY2QzZmZlYTk1NDJiNiIsImlhdCI6MTY0OTM1NjQzOCwiZXhwIjoxNjQ5MzYwMDM4fQ.1nOqLx_A_nFLvX_A62etSF0AVsbDceFuWvHBxhq26tc

{
    "title": "AAAAAA",
    "author": "Test Test",
	"url": "www.amazon.com",
	"likes": 1,
	"userId": "624ef410690edf7d8186c95f"
}